Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Diagnostics;
using Video_conference_app.Data;
using Video_conference_app.Models;

namespace Video_conference_app.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private readonly Video_conference_appContext _context;

        /*public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }*/
        
        public HomeController(ILogger<HomeController> logger, Video_conference_appContext context)
        {
            _logger = logger;
            _context = context;
        }

        /*public IActionResult Index()
        {
            return View();
        }*/


        public IActionResult Index()
        {
            var userData = HttpContext.Session.GetString("User");

            if (!string.IsNullOrEmpty(userData))
            {
                var user = JsonConvert.DeserializeObject<User>(userData);
                int id = user.Id;

                var currentTime = DateTime.Now;

                // Retrieve the most close meeting for the current user
                var closestMeeting = _context.Schedule
                    .Where(s => s.OrganizerId == id && s.StartTime > currentTime)
                    .OrderBy(s => s.StartTime) 
                    .FirstOrDefault(); 

                return View(closestMeeting); // Pass the closest meeting to the view
            }
            else
            {
                // If user is not logged in or has no meetings, return the view without any data
                return View(null);
            }
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SchedulesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Video_conference_app.Data;
using Video_conference_app.Models;

namespace Video_conference_app.Controllers
{
    public class SchedulesController : Controller
    {
        private readonly Video_conference_appContext _context;

        public SchedulesController(Video_conference_appContext context)
        {
            _context = context;
        }

        //Index page to show all sceduled meetings for current user
        public IActionResult Index()
        {            
            var userData = HttpContext.Session.GetString("User");

            if (!string.IsNullOrEmpty(userData))
            {
                var user = JsonConvert.DeserializeObject<User>(userData);
                string name = user.Name;
                int id = user.Id;

                var currentTime = DateTime.Now;                               
                var schedules = _context.Schedule
                            .Where(s => s.OrganizerId == id && s.StartTime > currentTime)
                            .OrderBy(s => s.StartTime) 
                            .ToList();

                return View(schedules);
            }
            else
            {     
                //redirect to Sign In  page of user is not logged in
                return RedirectToAction("SignIn", "Users"); ;
            }
        }


        // GET: Schedules/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schedule = await _context.Schedule
                .Include(s => s.Organizer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (schedule == null)
            {
                return NotFound();
            }

            return View(schedule);
        }
        

        // GET: Schedules/Create        
        public IActionResult Create()
        {
            var userData = HttpContext.Session.GetString("User");

            if (!string.IsNullOrEmpty(userData))
            {
                var user = JsonConvert.DeserializeObject<User>(userData);
                int id = user.Id;

                ViewData["OrganizerId"] = new SelectList(_context.User, "Id", "Email", id);

                return View();
            }
            else
            {
                // Redirect to the Sign In page if the user is not logged in
                return RedirectToAction("SignIn", "Users");
            }
        }

        // POST: Schedules/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,StartTime")] Schedule schedule)
        {
            var userData = HttpContext.Session.GetString("User");

            if (!string.IsNullOrEmpty(userData))
            {
                var user = JsonConvert.DeserializeObject<User>(userData);
                int id = user.Id;
                schedule.OrganizerId = id;                
                User currentUser = await _context.User.FindAsync(id);
                schedule.Organizer = currentUser;

                schedule.OrganizerId = id;                
                schedule.Organizer = currentUser;
          
                _context.Add(schedule);                
                await _context.SaveChangesAsync();

                // Redirect to the Index action
                return RedirectToAction(nameof(Index));

                // If model state is not valid, return the view with the provided schedule
                ViewData["OrganizerId"] = new SelectList(_context.User, "Id", "Email", id);
                return View(schedule);
            }
            else
            {
                // Redirect to the Sign In page if the user is not logged in
                return RedirectToAction("SignIn", "Users");
            }
        }


        // GET: Schedules/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schedule = await _context.Schedule
                .Include(s => s.Organizer)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (schedule == null)
            {
                return NotFound();
            }

            ViewData["OrganizerName"] = schedule.Organizer.Name;
            ViewData["OrganizerEmail"] = schedule.Organizer.Email;

            return View(schedule);
        }


        // POST: Schedules/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,StartTime")] Schedule schedule)
        {
            if (id != schedule.Id)
            {
                return NotFound();
            }

            // Retrieve the existing schedule from the database
            var existingSchedule = await _context.Schedule
                .Include(s => s.Organizer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (existingSchedule == null)
            {
                return NotFound();
            }

            schedule.Organizer = existingSchedule.Organizer;
            schedule.OrganizerId = existingSchedule.OrganizerId;

            // Update the other properties with the new values
            existingSchedule.Title = schedule.Title;
            existingSchedule.StartTime = schedule.StartTime;

            
                try
                {
                    _context.Update(existingSchedule); // Update the existing schedule entity
                    await _context.SaveChangesAsync(); // Save changes to the database
                    return RedirectToAction(nameof(Index)); // Redirect to Index page after successful save
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ScheduleExists(existingSchedule.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

            // If ModelState is not valid, return the view with the existing schedule
            return View(existingSchedule);
        }


        // GET: Schedules/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schedule = await _context.Schedule
                .Include(s => s.Organizer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (schedule == null)
            {
                return NotFound();
            }

            return View(schedule);
        }

        // POST: Schedules/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var schedule = await _context.Schedule.FindAsync(id);
            if (schedule != null)
            {
                _context.Schedule.Remove(schedule);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ScheduleExists(int id)
        {
            return _context.Schedule.Any(e => e.Id == id);
        }
    }
}

Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Video_conference_app.Data;
using Video_conference_app.Models;

namespace Video_conference_app.Controllers
{
    public class UsersController : Controller
    {
        private readonly Video_conference_appContext _context;

        public UsersController(Video_conference_appContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            return View(await _context.User.ToListAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Email,Password")] User user, string ConfirmPassword)
        {
            if (ModelState.IsValid)
            {
                if (ConfirmPassword == user.Password)
                {
                    _context.Add(user);
                    await _context.SaveChangesAsync();
                    TempData["Success"] = "Account created successfully!";
                    HttpContext.Session.SetString("User", JsonConvert.SerializeObject(user));
                    return RedirectToAction(nameof(HomeController.Index), "Home");
                }

                TempData["Error"] = "Passwords have to equal";
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Email,Password")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                    TempData["Info"] = "Account was successfully updated!";
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.User.FindAsync(id);
            if (user != null)
            {
                _context.User.Remove(user);
            }

            await _context.SaveChangesAsync();
            HttpContext.Session.Clear();
            TempData["Info"] = "Account was successfully deleted!";
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }

        private bool UserExists(int id)
        {
            return _context.User.Any(e => e.Id == id);
        }
        
        // GET: Users/SignIn
        public IActionResult SignIn()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SignIn([Bind("Email,Password")] User user)
        {
            var activeUser = await _context.User.FirstOrDefaultAsync(u => u.Email == user.Email && u.Password == user.Password);

            if (activeUser != null)
            {
                TempData["Success"] = "Log in successful!";
                HttpContext.Session.SetString("User", JsonConvert.SerializeObject(activeUser));
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }
            else
            {
                TempData["Error"] = "Incorrect email or password!";
            }

            return View(user);
        }

        public IActionResult LogOut()
        {
            HttpContext.Session.Clear();
            TempData["Info"] = "You are logged out of your account!";
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }
    }
}

Views/Home/Index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
@if (TempData["Success"] != null)
{
    <div class="alert alert-success">
        @TempData["Success"]
    </div>
}
@if(TempData["Info"] != null)
{
    <div class="alert alert-info">
        @TempData["Info"]
    </div>
}


<header class="text-center mt-5">
    <h1>Welcome to MeetingHub!</h1>
    <p>Streamline your meeting management with ease.</p>
</header>

<div class="container mt-5">
    <div class="row">
        <div class="col-md-6">
            <a asp-controller="Chat" asp-action="HostChat" type="button" class="btn btn-primary btn-block mb-3">
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 20 20">
                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"/>
                    <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"/>
                </svg>
                Create Meeting
            </a>
        </div>
        <div class="col-md-6">
            <a asp-controller="Schedules" asp-action="Index" class="btn btn-primary btn-block mb-3">
                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-calendar2-plus" viewBox="0 0 20 20">
                    <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5M2 2a1 1 0 0 0-1 1v11a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1z"/>
                    <path d="M2.5 4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5H3a.5.5 0 0 1-.5-.5zM8 8a.5.5 0 0 1 .5.5V10H10a.5.5 0 0 1 0 1H8.5v1.5a.5.5 0 0 1-1 0V11H6a.5.5 0 0 1 0-1h1.5V8.5A.5.5 0 0 1 8 8"/>
                </svg> Schedule Meeting
            </a>
        </div>
    </div>

    @{
    var user = Context.Session.GetString("User");
    }

    @if (string.IsNullOrEmpty(user))
    {
        <div class="row">
            <div class="col-md-6">
                <a asp-controller="Users" asp-action="SignIn" class="btn btn-primary btn-block mb-3">
                    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-person-up" viewBox="0 0 20 20">
                        <path d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7m.354-5.854 1.5 1.5a.5.5 0 0 1-.708.708L13 11.707V14.5a.5.5 0 0 1-1 0v-2.793l-.646.647a.5.5 0 0 1-.708-.708l1.5-1.5a.5.5 0 0 1 .708 0M11 5a3 3 0 1 1-6 0 3 3 0 0 1 6 0M8 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4"/>
                        <path d="M8.256 14a4.5 4.5 0 0 1-.229-1.004H3c.001-.246.154-.986.832-1.664C4.484 10.68 5.711 10 8 10q.39 0 .74.025c.226-.341.496-.65.804-.918Q8.844 9.002 8 9c-5 0-6 3-6 4s1 1 1 1z"/>
                    </svg>
                    Sign In
                </a>
            </div>
            <div class="col-md-6">
                <a asp-controller="Users" asp-action="Create" class="btn btn-primary btn-block mb-3">
                    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-person-plus-fill" viewBox="0 0 20 20">
                        <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6"/>
                        <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5"/>
                    </svg>
                    Sign Up
                </a>
            </div>
        </div>
    }
    <div class="row">
        <div class="col-md-12">
             <a asp-controller="Chat" asp-action="Index" type="button" class="btn btn btn-success btn-block" color="orange">
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-telephone-fill" viewBox="0 0 20 20">
                    <path fill-rule="evenodd" d="M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.68.68 0 0 0 .178.643l2.457 2.457a.68.68 0 0 0 .644.178l2.189-.547a1.75 1.75 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.6 18.6 0 0 1-7.01-4.42 18.6 18.6 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877z"/>
                </svg>
                Join Meeting
            </a>
        </div>
    </div>
</div>

    <style>
    .card-container {
        position: fixed;
        bottom: 20px;
        right: 20px;
        z-index: 1000;
        max-width: 300px; 
    }

    .card {
        width: 100%; 
    }

    .card-body {
        max-height: 150px; 
        overflow-y: auto; 
    }

    .card:hover {
            background-color: #ffdd72;
    }
</style>

<div class="card-container">
    <div class="card border border-warning">
        <div class="card-body text-dark">
            @if (Model != null)
            {
                <h5 class="card-title">Most Closest Meeting:</h5>
                <p class="card-text">Title: @Model.Title</p>
                <p class="card-text">Start Time: @Model.StartTime.ToString("yyyy-MM-dd HH:mm")</p>
            }
            else
            {
                <p class="card-text">No meetings scheduled.</p>
            }
        </div>
    </div>
</div>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>